### ISSUE TITLE
Fix error with  st.session_state['threat_model'] not defined

### ISSUE THREAD

**Issue by Deloitte-ngerard** [Deloitte-ngerard/DevSecOps-GenAI#5]
In main.py, find out where we're trying to access  st.session_state['threat_model']  before defining it.

**Comment by nikhilanaidu** [comment]
I think it was initializing error, which I set it to none.
if 'threat_model' not in st.session_state:
    st.session_state['threat_model'] = None 
Added these lines, before this
if st.session_state['threat_model']:
